Fix errors reported by mypy (#490)
* Strings, not objects

Fixes one mypy-detected error:

Type of __all__ must be "Sequence[str]", not "List[object]"

Towards resolving #489

* Fix __all__ in another module, use single quotes

* Add typing to request dict

Resolves the error

Incompatible types in assignment (expression has type "bool",
target has type "Collection[Any]")

* Our auth.Auth isn't type-compatible with httpx.AsyncClient

Added a new AuthType alias for httpx.Auth, added a missing
abstract method.

* Fix mypy errors in order_requests

* Strictly guard against having no status bar in reporting.py

And ignore mypy warnings about modules with no typing or stubs.

* Always set email flag in search request

Removes a conditional statement and eliminates one of the original
mypy errors.